### ISSUE TITLE
Please Make Source Code Available

### ISSUE THREAD

**Issue by robmyers** [ethereum/emacs-solidity#1]
Heya.

I code in Emacs, and I did write modes for lll and (old) Serpent. I'd like to not re-invent the wheel if there's an existing Solidity mode. Is it ready for use yet?

Thanks.

**Comment by LefterisJP** [comment]
hey rob, yeah it's totally experimental and I don't have lots of time to spend on it right now since Solidity itself takes all of my time but yeah I will put it on here. For now it's just syntax highlighting. Afterwards I am thinking of interfacing with the solidity libraries to provide for other more IDE-like features.
