### ISSUE TITLE
flycheck doesnt work because it needs to copy things for import into /tmp

### ISSUE THREAD

**Issue by kootenpv** [ethereum/emacs-solidity#7]
The checks fail because it transfers the contract to the tmp folder and that doesn't work for imports.

**Comment by LefterisJP** [comment]
I will have a look. Thank you for reporting this.

**Comment by LefterisJP** [comment]
@kootenpv Fixed it. Latest flycheck version should now work perfectly with the solidity mode.

In case you would like to ever make your own flycheck checker the trick is here:
```lisp
    :command ("/usr/bin/solc" source-inplace)
```

I had it as `source` before which was copying the source to some temporary folder, but now it is doing the checks in place so that imports work.
